//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFinderContracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFinderContracts.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input matrix elements must have all the same lenght.
        /// </summary>
        public static string MatrixAllElementsMustHaveSameSize {
            get {
                return ResourceManager.GetString("MatrixAllElementsMustHaveSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input matrix cannot be empty.
        /// </summary>
        public static string MatrixCannotBeEmpty {
            get {
                return ResourceManager.GetString("MatrixCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input matrix cannot be null.
        /// </summary>
        public static string MatrixCannotBeNull {
            get {
                return ResourceManager.GetString("MatrixCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input matrix cannot exceed {0} elements.
        /// </summary>
        public static string MatrixCannotExceedElementsCount {
            get {
                return ResourceManager.GetString("MatrixCannotExceedElementsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input matrix element at position {0} exceeds max size of {1}.
        /// </summary>
        public static string MatrixElementCannotExceedSize {
            get {
                return ResourceManager.GetString("MatrixElementCannotExceedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input matrix elements cannot exceed size of {0}.
        /// </summary>
        public static string MatrixElementsCannotExceedSize {
            get {
                return ResourceManager.GetString("MatrixElementsCannotExceedSize", resourceCulture);
            }
        }
    }
}
